/**
 * This file was automatically generated by openapi-codegeneration.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source OpenAPI file,
 * and run openapi-codegeneration to regenerate this file.
 */
import * as Types from './types.js';

/**
 * Typing for all possible responses to the request made by listInstitutions()
 * @category listInstitutions()
 */
export type ListInstitutionsResponse =
  | ListInstitutionsSuccessResponse
  | ListInstitutionsErrorResponse;

/**
 * Typing for all successful responses to the request made by listInstitutions()
 * @category listInstitutions()
 */
export type ListInstitutionsSuccessResponse = ListInstitutionsResponse200;

/**
 * Typing for all error responses to the request made by listInstitutions()
 * @category listInstitutions()
 */
export type ListInstitutionsErrorResponse =
  | ListInstitutionsResponse400
  | ListInstitutionsResponse401
  | ListInstitutionsResponse403
  | ListInstitutionsResponse404
  | ListInstitutionsResponse500;

/**
 * Typing for a response with status 200 to the request made by listInstitutions()
 * @category listInstitutions()
 */
export interface ListInstitutionsResponse200 extends Types.SuccessResponse {
  status: 200;
  headers?: {
    [k: string]: string | undefined;
  };
  body: Types.Institution<'response'>[];
}

/**
 * Typing for a response with status 400 to the request made by listInstitutions()
 * @category listInstitutions()
 */
export interface ListInstitutionsResponse400 extends Types.ErrorResponse {
  status: 400;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 401 to the request made by listInstitutions()
 * @category listInstitutions()
 */
export interface ListInstitutionsResponse401 extends Types.ErrorResponse {
  status: 401;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 403 to the request made by listInstitutions()
 * @category listInstitutions()
 */
export interface ListInstitutionsResponse403 extends Types.ErrorResponse {
  status: 403;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 404 to the request made by listInstitutions()
 * @category listInstitutions()
 */
export interface ListInstitutionsResponse404 extends Types.ErrorResponse {
  status: 404;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 500 to the request made by listInstitutions()
 * @category listInstitutions()
 */
export interface ListInstitutionsResponse500 extends Types.ErrorResponse {
  status: 500;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for the body of the request made by createInstitution()
 * @category createInstitution()
 */
export type CreateInstitutionBody = Types.Institution<'request'>;

/**
 * Typing for all possible responses to the request made by createInstitution()
 * @category createInstitution()
 */
export type CreateInstitutionResponse =
  | CreateInstitutionSuccessResponse
  | CreateInstitutionErrorResponse;

/**
 * Typing for all successful responses to the request made by createInstitution()
 * @category createInstitution()
 */
export type CreateInstitutionSuccessResponse = CreateInstitutionResponse201;

/**
 * Typing for all error responses to the request made by createInstitution()
 * @category createInstitution()
 */
export type CreateInstitutionErrorResponse =
  | CreateInstitutionResponse400
  | CreateInstitutionResponse401
  | CreateInstitutionResponse403
  | CreateInstitutionResponse404
  | CreateInstitutionResponse500;

/**
 * Typing for a response with status 201 to the request made by createInstitution()
 * @category createInstitution()
 */
export interface CreateInstitutionResponse201 extends Types.SuccessResponse {
  status: 201;
  headers?: {
    [k: string]: string | undefined;
  };
  body: Types.Institution<'response'>;
}

/**
 * Typing for a response with status 400 to the request made by createInstitution()
 * @category createInstitution()
 */
export interface CreateInstitutionResponse400 extends Types.ErrorResponse {
  status: 400;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 401 to the request made by createInstitution()
 * @category createInstitution()
 */
export interface CreateInstitutionResponse401 extends Types.ErrorResponse {
  status: 401;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 403 to the request made by createInstitution()
 * @category createInstitution()
 */
export interface CreateInstitutionResponse403 extends Types.ErrorResponse {
  status: 403;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 404 to the request made by createInstitution()
 * @category createInstitution()
 */
export interface CreateInstitutionResponse404 extends Types.ErrorResponse {
  status: 404;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 500 to the request made by createInstitution()
 * @category createInstitution()
 */
export interface CreateInstitutionResponse500 extends Types.ErrorResponse {
  status: 500;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for the parameters of the request made by getInstitution()
 * @category getInstitution()
 */
export type GetInstitutionParameters = {
  institution_id: string;
};

/**
 * Typing for all possible responses to the request made by getInstitution()
 * @category getInstitution()
 */
export type GetInstitutionResponse =
  | GetInstitutionSuccessResponse
  | GetInstitutionErrorResponse;

/**
 * Typing for all successful responses to the request made by getInstitution()
 * @category getInstitution()
 */
export type GetInstitutionSuccessResponse = GetInstitutionResponse200;

/**
 * Typing for all error responses to the request made by getInstitution()
 * @category getInstitution()
 */
export type GetInstitutionErrorResponse =
  | GetInstitutionResponse400
  | GetInstitutionResponse401
  | GetInstitutionResponse403
  | GetInstitutionResponse404
  | GetInstitutionResponse500;

/**
 * Typing for a response with status 200 to the request made by getInstitution()
 * @category getInstitution()
 */
export interface GetInstitutionResponse200 extends Types.SuccessResponse {
  status: 200;
  headers?: {
    [k: string]: string | undefined;
  };
  body: Types.Institution<'response'>;
}

/**
 * Typing for a response with status 400 to the request made by getInstitution()
 * @category getInstitution()
 */
export interface GetInstitutionResponse400 extends Types.ErrorResponse {
  status: 400;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 401 to the request made by getInstitution()
 * @category getInstitution()
 */
export interface GetInstitutionResponse401 extends Types.ErrorResponse {
  status: 401;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 403 to the request made by getInstitution()
 * @category getInstitution()
 */
export interface GetInstitutionResponse403 extends Types.ErrorResponse {
  status: 403;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 404 to the request made by getInstitution()
 * @category getInstitution()
 */
export interface GetInstitutionResponse404 extends Types.ErrorResponse {
  status: 404;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 500 to the request made by getInstitution()
 * @category getInstitution()
 */
export interface GetInstitutionResponse500 extends Types.ErrorResponse {
  status: 500;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for the parameters of the request made by updateInstitution()
 * @category updateInstitution()
 */
export type UpdateInstitutionParameters = {
  institution_id: string;
};

/**
 * Typing for the body of the request made by updateInstitution()
 * @category updateInstitution()
 */
export type UpdateInstitutionBody = Types.Institution<'request'> | undefined;

/**
 * Typing for all possible responses to the request made by updateInstitution()
 * @category updateInstitution()
 */
export type UpdateInstitutionResponse =
  | UpdateInstitutionSuccessResponse
  | UpdateInstitutionErrorResponse;

/**
 * Typing for all successful responses to the request made by updateInstitution()
 * @category updateInstitution()
 */
export type UpdateInstitutionSuccessResponse = UpdateInstitutionResponse200;

/**
 * Typing for all error responses to the request made by updateInstitution()
 * @category updateInstitution()
 */
export type UpdateInstitutionErrorResponse =
  | UpdateInstitutionResponse400
  | UpdateInstitutionResponse401
  | UpdateInstitutionResponse403
  | UpdateInstitutionResponse404
  | UpdateInstitutionResponse500;

/**
 * Typing for a response with status 200 to the request made by updateInstitution()
 * @category updateInstitution()
 */
export interface UpdateInstitutionResponse200 extends Types.SuccessResponse {
  status: 200;
  headers?: {
    [k: string]: string | undefined;
  };
  body: Types.Institution<'response'>;
}

/**
 * Typing for a response with status 400 to the request made by updateInstitution()
 * @category updateInstitution()
 */
export interface UpdateInstitutionResponse400 extends Types.ErrorResponse {
  status: 400;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 401 to the request made by updateInstitution()
 * @category updateInstitution()
 */
export interface UpdateInstitutionResponse401 extends Types.ErrorResponse {
  status: 401;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 403 to the request made by updateInstitution()
 * @category updateInstitution()
 */
export interface UpdateInstitutionResponse403 extends Types.ErrorResponse {
  status: 403;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 404 to the request made by updateInstitution()
 * @category updateInstitution()
 */
export interface UpdateInstitutionResponse404 extends Types.ErrorResponse {
  status: 404;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 500 to the request made by updateInstitution()
 * @category updateInstitution()
 */
export interface UpdateInstitutionResponse500 extends Types.ErrorResponse {
  status: 500;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for the parameters of the request made by deleteInstitution()
 * @category deleteInstitution()
 */
export type DeleteInstitutionParameters = {
  institution_id: string;
};

/**
 * Typing for all possible responses to the request made by deleteInstitution()
 * @category deleteInstitution()
 */
export type DeleteInstitutionResponse =
  | DeleteInstitutionSuccessResponse
  | DeleteInstitutionErrorResponse;

/**
 * Typing for all successful responses to the request made by deleteInstitution()
 * @category deleteInstitution()
 */
export type DeleteInstitutionSuccessResponse = DeleteInstitutionResponse204;

/**
 * Typing for all error responses to the request made by deleteInstitution()
 * @category deleteInstitution()
 */
export type DeleteInstitutionErrorResponse =
  | DeleteInstitutionResponse400
  | DeleteInstitutionResponse401
  | DeleteInstitutionResponse403
  | DeleteInstitutionResponse404
  | DeleteInstitutionResponse500;

/**
 * Typing for a response with status 204 to the request made by deleteInstitution()
 * @category deleteInstitution()
 */
export interface DeleteInstitutionResponse204 extends Types.SuccessResponse {
  status: 204;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 400 to the request made by deleteInstitution()
 * @category deleteInstitution()
 */
export interface DeleteInstitutionResponse400 extends Types.ErrorResponse {
  status: 400;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 401 to the request made by deleteInstitution()
 * @category deleteInstitution()
 */
export interface DeleteInstitutionResponse401 extends Types.ErrorResponse {
  status: 401;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 403 to the request made by deleteInstitution()
 * @category deleteInstitution()
 */
export interface DeleteInstitutionResponse403 extends Types.ErrorResponse {
  status: 403;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 404 to the request made by deleteInstitution()
 * @category deleteInstitution()
 */
export interface DeleteInstitutionResponse404 extends Types.ErrorResponse {
  status: 404;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 500 to the request made by deleteInstitution()
 * @category deleteInstitution()
 */
export interface DeleteInstitutionResponse500 extends Types.ErrorResponse {
  status: 500;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for the parameters of the request made by proxyGet()
 * @category proxyGet()
 */
export type ProxyGetParameters = {
  URL?: string;
};

/**
 * Typing for all possible responses to the request made by proxyGet()
 * @category proxyGet()
 */
export type ProxyGetResponse = ProxyGetSuccessResponse | ProxyGetErrorResponse;

/**
 * Typing for all successful responses to the request made by proxyGet()
 * @category proxyGet()
 */
export type ProxyGetSuccessResponse =
  | ProxyGetResponse1XX
  | ProxyGetResponse2XX
  | ProxyGetResponse3XX;

/**
 * Typing for all error responses to the request made by proxyGet()
 * @category proxyGet()
 */
export type ProxyGetErrorResponse = ProxyGetResponse4XX | ProxyGetResponse5XX;

/**
 * Typing for a response with status 1XX to the request made by proxyGet()
 * @category proxyGet()
 */
export interface ProxyGetResponse1XX extends Types.SuccessResponse {
  status: Types.NumericRange<100, 199>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 2XX to the request made by proxyGet()
 * @category proxyGet()
 */
export interface ProxyGetResponse2XX extends Types.SuccessResponse {
  status: Types.NumericRange<200, 299>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 3XX to the request made by proxyGet()
 * @category proxyGet()
 */
export interface ProxyGetResponse3XX extends Types.SuccessResponse {
  status: Types.NumericRange<300, 399>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 4XX to the request made by proxyGet()
 * @category proxyGet()
 */
export interface ProxyGetResponse4XX extends Types.ErrorResponse {
  status: Types.NumericRange<400, 499>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 5XX to the request made by proxyGet()
 * @category proxyGet()
 */
export interface ProxyGetResponse5XX extends Types.ErrorResponse {
  status: Types.NumericRange<500, 599>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for the parameters of the request made by proxyPost()
 * @category proxyPost()
 */
export type ProxyPostParameters = {
  URL?: string;
};

/**
 * Typing for all possible responses to the request made by proxyPost()
 * @category proxyPost()
 */
export type ProxyPostResponse = ProxyPostSuccessResponse | ProxyPostErrorResponse;

/**
 * Typing for all successful responses to the request made by proxyPost()
 * @category proxyPost()
 */
export type ProxyPostSuccessResponse =
  | ProxyPostResponse1XX
  | ProxyPostResponse2XX
  | ProxyPostResponse3XX;

/**
 * Typing for all error responses to the request made by proxyPost()
 * @category proxyPost()
 */
export type ProxyPostErrorResponse = ProxyPostResponse4XX | ProxyPostResponse5XX;

/**
 * Typing for a response with status 1XX to the request made by proxyPost()
 * @category proxyPost()
 */
export interface ProxyPostResponse1XX extends Types.SuccessResponse {
  status: Types.NumericRange<100, 199>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 2XX to the request made by proxyPost()
 * @category proxyPost()
 */
export interface ProxyPostResponse2XX extends Types.SuccessResponse {
  status: Types.NumericRange<200, 299>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 3XX to the request made by proxyPost()
 * @category proxyPost()
 */
export interface ProxyPostResponse3XX extends Types.SuccessResponse {
  status: Types.NumericRange<300, 399>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 4XX to the request made by proxyPost()
 * @category proxyPost()
 */
export interface ProxyPostResponse4XX extends Types.ErrorResponse {
  status: Types.NumericRange<400, 499>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 5XX to the request made by proxyPost()
 * @category proxyPost()
 */
export interface ProxyPostResponse5XX extends Types.ErrorResponse {
  status: Types.NumericRange<500, 599>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for the parameters of the request made by proxyPut()
 * @category proxyPut()
 */
export type ProxyPutParameters = {
  URL?: string;
};

/**
 * Typing for all possible responses to the request made by proxyPut()
 * @category proxyPut()
 */
export type ProxyPutResponse = ProxyPutSuccessResponse | ProxyPutErrorResponse;

/**
 * Typing for all successful responses to the request made by proxyPut()
 * @category proxyPut()
 */
export type ProxyPutSuccessResponse =
  | ProxyPutResponse1XX
  | ProxyPutResponse2XX
  | ProxyPutResponse3XX;

/**
 * Typing for all error responses to the request made by proxyPut()
 * @category proxyPut()
 */
export type ProxyPutErrorResponse = ProxyPutResponse4XX | ProxyPutResponse5XX;

/**
 * Typing for a response with status 1XX to the request made by proxyPut()
 * @category proxyPut()
 */
export interface ProxyPutResponse1XX extends Types.SuccessResponse {
  status: Types.NumericRange<100, 199>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 2XX to the request made by proxyPut()
 * @category proxyPut()
 */
export interface ProxyPutResponse2XX extends Types.SuccessResponse {
  status: Types.NumericRange<200, 299>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 3XX to the request made by proxyPut()
 * @category proxyPut()
 */
export interface ProxyPutResponse3XX extends Types.SuccessResponse {
  status: Types.NumericRange<300, 399>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 4XX to the request made by proxyPut()
 * @category proxyPut()
 */
export interface ProxyPutResponse4XX extends Types.ErrorResponse {
  status: Types.NumericRange<400, 499>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 5XX to the request made by proxyPut()
 * @category proxyPut()
 */
export interface ProxyPutResponse5XX extends Types.ErrorResponse {
  status: Types.NumericRange<500, 599>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for the parameters of the request made by proxyPatch()
 * @category proxyPatch()
 */
export type ProxyPatchParameters = {
  URL?: string;
};

/**
 * Typing for all possible responses to the request made by proxyPatch()
 * @category proxyPatch()
 */
export type ProxyPatchResponse = ProxyPatchSuccessResponse | ProxyPatchErrorResponse;

/**
 * Typing for all successful responses to the request made by proxyPatch()
 * @category proxyPatch()
 */
export type ProxyPatchSuccessResponse =
  | ProxyPatchResponse1XX
  | ProxyPatchResponse2XX
  | ProxyPatchResponse3XX;

/**
 * Typing for all error responses to the request made by proxyPatch()
 * @category proxyPatch()
 */
export type ProxyPatchErrorResponse = ProxyPatchResponse4XX | ProxyPatchResponse5XX;

/**
 * Typing for a response with status 1XX to the request made by proxyPatch()
 * @category proxyPatch()
 */
export interface ProxyPatchResponse1XX extends Types.SuccessResponse {
  status: Types.NumericRange<100, 199>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 2XX to the request made by proxyPatch()
 * @category proxyPatch()
 */
export interface ProxyPatchResponse2XX extends Types.SuccessResponse {
  status: Types.NumericRange<200, 299>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 3XX to the request made by proxyPatch()
 * @category proxyPatch()
 */
export interface ProxyPatchResponse3XX extends Types.SuccessResponse {
  status: Types.NumericRange<300, 399>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 4XX to the request made by proxyPatch()
 * @category proxyPatch()
 */
export interface ProxyPatchResponse4XX extends Types.ErrorResponse {
  status: Types.NumericRange<400, 499>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 5XX to the request made by proxyPatch()
 * @category proxyPatch()
 */
export interface ProxyPatchResponse5XX extends Types.ErrorResponse {
  status: Types.NumericRange<500, 599>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for the parameters of the request made by proxyDelete()
 * @category proxyDelete()
 */
export type ProxyDeleteParameters = {
  URL?: string;
};

/**
 * Typing for all possible responses to the request made by proxyDelete()
 * @category proxyDelete()
 */
export type ProxyDeleteResponse = ProxyDeleteSuccessResponse | ProxyDeleteErrorResponse;

/**
 * Typing for all successful responses to the request made by proxyDelete()
 * @category proxyDelete()
 */
export type ProxyDeleteSuccessResponse =
  | ProxyDeleteResponse1XX
  | ProxyDeleteResponse2XX
  | ProxyDeleteResponse3XX;

/**
 * Typing for all error responses to the request made by proxyDelete()
 * @category proxyDelete()
 */
export type ProxyDeleteErrorResponse = ProxyDeleteResponse4XX | ProxyDeleteResponse5XX;

/**
 * Typing for a response with status 1XX to the request made by proxyDelete()
 * @category proxyDelete()
 */
export interface ProxyDeleteResponse1XX extends Types.SuccessResponse {
  status: Types.NumericRange<100, 199>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 2XX to the request made by proxyDelete()
 * @category proxyDelete()
 */
export interface ProxyDeleteResponse2XX extends Types.SuccessResponse {
  status: Types.NumericRange<200, 299>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 3XX to the request made by proxyDelete()
 * @category proxyDelete()
 */
export interface ProxyDeleteResponse3XX extends Types.SuccessResponse {
  status: Types.NumericRange<300, 399>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 4XX to the request made by proxyDelete()
 * @category proxyDelete()
 */
export interface ProxyDeleteResponse4XX extends Types.ErrorResponse {
  status: Types.NumericRange<400, 499>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 5XX to the request made by proxyDelete()
 * @category proxyDelete()
 */
export interface ProxyDeleteResponse5XX extends Types.ErrorResponse {
  status: Types.NumericRange<500, 599>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for the parameters of the request made by proxyHead()
 * @category proxyHead()
 */
export type ProxyHeadParameters = {
  URL?: string;
};

/**
 * Typing for all possible responses to the request made by proxyHead()
 * @category proxyHead()
 */
export type ProxyHeadResponse = ProxyHeadSuccessResponse | ProxyHeadErrorResponse;

/**
 * Typing for all successful responses to the request made by proxyHead()
 * @category proxyHead()
 */
export type ProxyHeadSuccessResponse =
  | ProxyHeadResponse1XX
  | ProxyHeadResponse2XX
  | ProxyHeadResponse3XX;

/**
 * Typing for all error responses to the request made by proxyHead()
 * @category proxyHead()
 */
export type ProxyHeadErrorResponse = ProxyHeadResponse4XX | ProxyHeadResponse5XX;

/**
 * Typing for a response with status 1XX to the request made by proxyHead()
 * @category proxyHead()
 */
export interface ProxyHeadResponse1XX extends Types.SuccessResponse {
  status: Types.NumericRange<100, 199>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 2XX to the request made by proxyHead()
 * @category proxyHead()
 */
export interface ProxyHeadResponse2XX extends Types.SuccessResponse {
  status: Types.NumericRange<200, 299>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 3XX to the request made by proxyHead()
 * @category proxyHead()
 */
export interface ProxyHeadResponse3XX extends Types.SuccessResponse {
  status: Types.NumericRange<300, 399>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 4XX to the request made by proxyHead()
 * @category proxyHead()
 */
export interface ProxyHeadResponse4XX extends Types.ErrorResponse {
  status: Types.NumericRange<400, 499>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 5XX to the request made by proxyHead()
 * @category proxyHead()
 */
export interface ProxyHeadResponse5XX extends Types.ErrorResponse {
  status: Types.NumericRange<500, 599>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for the parameters of the request made by proxyOptions()
 * @category proxyOptions()
 */
export type ProxyOptionsParameters = {
  URL?: string;
};

/**
 * Typing for all possible responses to the request made by proxyOptions()
 * @category proxyOptions()
 */
export type ProxyOptionsResponse =
  | ProxyOptionsSuccessResponse
  | ProxyOptionsErrorResponse;

/**
 * Typing for all successful responses to the request made by proxyOptions()
 * @category proxyOptions()
 */
export type ProxyOptionsSuccessResponse =
  | ProxyOptionsResponse1XX
  | ProxyOptionsResponse2XX
  | ProxyOptionsResponse3XX;

/**
 * Typing for all error responses to the request made by proxyOptions()
 * @category proxyOptions()
 */
export type ProxyOptionsErrorResponse = ProxyOptionsResponse4XX | ProxyOptionsResponse5XX;

/**
 * Typing for a response with status 1XX to the request made by proxyOptions()
 * @category proxyOptions()
 */
export interface ProxyOptionsResponse1XX extends Types.SuccessResponse {
  status: Types.NumericRange<100, 199>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 2XX to the request made by proxyOptions()
 * @category proxyOptions()
 */
export interface ProxyOptionsResponse2XX extends Types.SuccessResponse {
  status: Types.NumericRange<200, 299>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 3XX to the request made by proxyOptions()
 * @category proxyOptions()
 */
export interface ProxyOptionsResponse3XX extends Types.SuccessResponse {
  status: Types.NumericRange<300, 399>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 4XX to the request made by proxyOptions()
 * @category proxyOptions()
 */
export interface ProxyOptionsResponse4XX extends Types.ErrorResponse {
  status: Types.NumericRange<400, 499>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 5XX to the request made by proxyOptions()
 * @category proxyOptions()
 */
export interface ProxyOptionsResponse5XX extends Types.ErrorResponse {
  status: Types.NumericRange<500, 599>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for the parameters of the request made by proxyTrace()
 * @category proxyTrace()
 */
export type ProxyTraceParameters = {
  URL?: string;
};

/**
 * Typing for all possible responses to the request made by proxyTrace()
 * @category proxyTrace()
 */
export type ProxyTraceResponse = ProxyTraceSuccessResponse | ProxyTraceErrorResponse;

/**
 * Typing for all successful responses to the request made by proxyTrace()
 * @category proxyTrace()
 */
export type ProxyTraceSuccessResponse =
  | ProxyTraceResponse1XX
  | ProxyTraceResponse2XX
  | ProxyTraceResponse3XX;

/**
 * Typing for all error responses to the request made by proxyTrace()
 * @category proxyTrace()
 */
export type ProxyTraceErrorResponse = ProxyTraceResponse4XX | ProxyTraceResponse5XX;

/**
 * Typing for a response with status 1XX to the request made by proxyTrace()
 * @category proxyTrace()
 */
export interface ProxyTraceResponse1XX extends Types.SuccessResponse {
  status: Types.NumericRange<100, 199>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 2XX to the request made by proxyTrace()
 * @category proxyTrace()
 */
export interface ProxyTraceResponse2XX extends Types.SuccessResponse {
  status: Types.NumericRange<200, 299>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 3XX to the request made by proxyTrace()
 * @category proxyTrace()
 */
export interface ProxyTraceResponse3XX extends Types.SuccessResponse {
  status: Types.NumericRange<300, 399>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 4XX to the request made by proxyTrace()
 * @category proxyTrace()
 */
export interface ProxyTraceResponse4XX extends Types.ErrorResponse {
  status: Types.NumericRange<400, 499>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}

/**
 * Typing for a response with status 5XX to the request made by proxyTrace()
 * @category proxyTrace()
 */
export interface ProxyTraceResponse5XX extends Types.ErrorResponse {
  status: Types.NumericRange<500, 599>;
  headers?: {
    [k: string]: string | undefined;
  };
  body?: undefined;
}
