################################################################################
# Helper #######################################################################
################################################################################

helper/openapi-codegeneration:
  - script: build
  - script: lint
    dependencies:
      - helper/openapi-codegeneration:build
    tags:
      - test

helper/crosslab-typescript-addon:
  - script: build
    dependencies:
      - helper/openapi-codegeneration:build
  - script: lint
    dependencies:
      - helper/crosslab-typescript-addon:build
    tags:
      - test

helper/python-test-helper:
  - script: build
  - script: lint
    dependencies:
      - helper/python-test-helper:build
  - script: test
    dependencies:
      - helper/python-test-helper:build
      - helper/python-test-helper:lint
    tags:
      - test

helper/dummy-device/js:
  - script: build
    dependencies:
      - clients/api/js:build
      - clients/soa/js:build
      - clients/soa_services/electricalConnection/js:build
      - clients/soa_services/file/js:build
      - clients/soa_services/webcam/js:build
  - script: lint
    dependencies:
      - helper/dummy-device/js:build
    tags:
      - test

helper/dummy-device/python:
  - script: build
    dependencies:
      - clients/api/python:build
      - clients/soa/python:build
      - clients/soa_services/electricalConnection/python:build
  - script: lint
    dependencies:
      - helper/dummy-device/python:build
    tags:
      - test

################################################################################
# Backend ######################################################################
################################################################################

services/common:
  - script: build
  - script: lint
    dependencies:
      - services/common:build
    tags:
      - test

services/auth:
  - script: build-spec
    paths:
      - ./api
  - script: lint-spec
    paths:
      - ./api
    dependencies:
      - services/auth:build-spec
    tags:
      - test
  - script: build
    dependencies:
      - services/auth:build-spec
      - services/common:build
      - helper/crosslab-typescript-addon:build
      - helper/openapi-codegeneration:build
  - script: build-docker
    dependencies:
      - services/auth:build
  - script: lint
    dependencies:
      - services/auth:build
    tags:
      - test
  - script: test
    dependencies:
      - services/auth:build
      - services/auth:lint
    tags:
      - test

services/authorization:
  - script: build-spec
    paths:
      - ./api
  - script: lint-spec
    paths:
      - ./api
    dependencies:
      - services/authorization:build-spec
    tags:
      - test
  - script: build
    dependencies:
      - services/common:build
      - services/common:lint
  - script: build-docker
    dependencies:
      - services/authorization:build
  - script: lint
    dependencies:
      - services/authorization:build
    tags:
      - test
  - script: test
    dependencies:
      - services/authorization:build
      - services/authorization:lint
    tags:
      - test

services/booking/src/common:
  - script: build
    dependencies:
      - helper/crosslab-typescript-addon:build
      - helper/openapi-codegeneration:build
      - services/booking:build-spec

services/booking/src/device-reservation:
  - script: build
    dependencies:
      - services/booking/src/common:build
  - script: test
    dependencies:
      - services/booking/src/device-reservation:build
    tags:
      - test
  - script: build-docker
    dependencies:
      - services/booking/src/device-reservation:build

services/booking/src/test_common:
  - script: build
    dependencies:
      - services/booking/src/common:build
      - services/booking/src/device-reservation:build

services/booking/src/booking-backend:
  - script: build
    dependencies:
      - services/booking:build-spec
      - services/booking/src/test_common:build
  - script: test
    dependencies:
      - services/booking/src/booking-backend:build
    tags:
      - test
  - script: build-docker
    dependencies:
      - services/booking/src/booking-backend:build

services/booking/src/booking-frontend:
  - script: build
    dependencies:
      - services/booking:build-spec
      - services/booking/src/booking-backend:build
  - script: test
    dependencies:
      - services/booking/src/booking-frontend:build
    tags:
      - test
  - script: build-docker
    dependencies:
      - services/booking/src/booking-frontend:build

services/booking/src/schedule-service:
  - script: build
    dependencies:
      - services/booking:build-spec
      - services/common:build
      - services/booking/src/common:build
      - services/booking/src/test_common:build
      - helper/crosslab-typescript-addon:build
      - helper/openapi-codegeneration:build
  - script: test
    dependencies:
      - services/booking/src/schedule-service:build
    tags:
      - test
  - script: build-docker
    dependencies:
      - services/booking/src/schedule-service:build

services/booking:
  - script: build-spec
    paths:
    - ./api
  - script: lint-spec
    paths:
      - ./api
    dependencies:
      - services/booking:build-spec
    tags:
      - test

services/device:
  - script: build-spec
    paths:
      - ./api
  - script: lint-spec
    paths:
      - ./api
    dependencies:
      - services/device:build-spec
    tags:
      - test
  - script: build
    dependencies:
      - services/device:build-spec
      - services/common:build
      - helper/crosslab-typescript-addon:build
      - helper/openapi-codegeneration:build
      - clients/api/js:build
  - script: build-docker
    dependencies:
      - services/device:build
#  - script: test
#    dependencies:
#      - services/device:build
#    tags:
#      - test

services/experiment:
  - script: build-spec
    paths:
      - ./api
  - script: lint-spec
    paths:
      - ./api
    dependencies:
      - services/experiment:build-spec
    tags:
      - test
  - script: build
    dependencies:
      - services/experiment:build-spec
      - services/common:build
      - helper/crosslab-typescript-addon:build
      - helper/openapi-codegeneration:build
      - clients/api/js:build
  - script: build-docker
    dependencies:
      - services/experiment:build
  - script: lint
    dependencies:
      - services/experiment:build
    tags:
      - test

services/federation:
  - script: build-spec
    paths:
      - ./api
  - script: lint-spec
    paths:
      - ./api
    dependencies:
      - services/federation:build-spec
    tags:
      - test
  - script: build
    dependencies:
      - services/federation:build-spec
      - services/common:build
      - helper/crosslab-typescript-addon:build
      - helper/openapi-codegeneration:build
      - clients/api/js:build
  - script: build-docker
    dependencies:
      - services/federation:build

services/lti:
  - script: build-spec
    paths:
      - ./api
  - script: lint-spec
    paths:
      - ./api
    dependencies:
      - services/lti:build-spec
    tags:
      - test
  - script: build
    dependencies:
      - services/lti:build-spec
      - services/common:build
      - helper/crosslab-typescript-addon:build
      - helper/openapi-codegeneration:build
      - clients/api/js:build
  - script: build-docker
    dependencies:
      - services/lti:build
  - script: test
    dependencies:
      - services/authorization:build
    tags:
      - test

services/openapi:
  - script: build
    dependencies:
      - services/auth:build-spec
      - services/booking:build-spec
      - services/device:build-spec
      - services/experiment:build-spec
      - services/federation:build-spec
      - services/lti:build-spec
  - script: lint
    dependencies:
      - services/openapi:build
    tags:
      - test

services/gateway:
  - script: build
  - script: build-docker
    dependencies:
      - services/gateway:build

################################################################################
# Clients ######################################################################
################################################################################

clients/api/js:
  - script: build
    dependencies:
      - services/auth:build-spec
      - services/booking:build-spec
      - services/device:build-spec
      - services/experiment:build-spec
      - services/federation:build-spec
      - helper/crosslab-typescript-addon:build
      - helper/openapi-codegeneration:build
      - services/openapi:build
  - script: lint
    dependencies:
      - clients/api/js:build
    tags:
      - test

clients/api/python:
  - script: build
    dependencies:
      - services/openapi:build
      - helper/openapi-codegeneration:build
  - script: lint
    dependencies:
      - clients/api/python:build
    tags:
      - test
  - script: test
    dependencies:
      - clients/api/python:build
      - clients/api/python:lint
    tags:
      - test

clients/soa/python:
  - script: build
    dependencies:
      - services/openapi:build
      - helper/openapi-codegeneration:build
      - clients/api/python:build
  - script: lint
    dependencies:
      - clients/soa/python:build
    tags:
      - test
  - script: test
    dependencies:
      - clients/api/python:test
      - clients/soa/python:build
      - clients/soa/python:lint
      - helper/python-test-helper:test
    tags:
      - test

clients/soa/js:
  - script: build
  - script: lint
    dependencies:
      - clients/soa/js:build
    tags:
      - test

# SOA Service ##################################################################

clients/soa_services/electricalConnection/python:
  - script: build
    dependencies:
      - helper/openapi-codegeneration:build
      - clients/api/python:build
      - clients/soa/python:build
  - script: lint
    dependencies:
      - clients/soa_services/electricalConnection/python:build
    tags:
      - test
  - script: test
    dependencies:
      - clients/api/python:test
      - clients/soa/python:test
      - clients/soa_services/electricalConnection/python:build
      - clients/soa_services/electricalConnection/python:lint
      - helper/python-test-helper:test
    tags:
      - test

clients/soa_services/electricalConnection/js:
  - script: build
    dependencies:
      - clients/soa/js:build
  - script: lint
    dependencies:
      - clients/soa_services/electricalConnection/js:build
    tags:
      - test

clients/soa_services/webcam/python:
  - script: build
    dependencies:
      - clients/api/python:build
      - clients/soa/python:build
  - script: lint
    dependencies:
      - clients/soa_services/webcam/python:build
    tags:
      - test
  - script: test
    dependencies:
      - clients/api/python:test
      - clients/soa/python:test
      - clients/soa_services/webcam/python:build
      - clients/soa_services/webcam/python:lint
      - helper/python-test-helper:test
    tags:
      - test

clients/soa_services/webcam/js:
  - script: build
    dependencies:
      - clients/soa/js:build
  - script: lint
    dependencies:
      - clients/soa_services/webcam/js:build
    tags:
      - test

clients/soa_services/file/python:
  - script: build
    dependencies:
      - clients/api/python:build
      - clients/soa/python:build
  - script: lint
    dependencies:
      - clients/soa_services/file/python:build
    tags:
      - test
  - script: test
    dependencies:
      - clients/api/python:test
      - clients/soa/python:test
      - clients/soa_services/file/python:build
      - clients/soa_services/file/python:lint
      - helper/python-test-helper:test
    tags:
      - test

clients/soa_services/file/js:
  - script: build
    dependencies:
      - clients/soa/js:build
  - script: lint
    dependencies:
      - clients/soa_services/file/js:build
    tags:
      - test

clients/soa_services/message/python:
  - script: build
    dependencies:
      - clients/api/python:build
      - clients/soa/python:build
  - script: lint
    dependencies:
      - clients/soa_services/message/python:build
    tags:
      - test
  - script: test
    dependencies:
      - clients/api/python:test
      - clients/soa/python:test
      - clients/soa_services/message/python:build
      - clients/soa_services/message/python:lint
      - helper/python-test-helper:test
    tags:
      - test

clients/soa_services/message/js:
  - script: build
    dependencies:
      - clients/soa/js:build
  - script: lint
    dependencies:
      - clients/soa_services/message/js:build
    tags:
      - test

clients/soa_services/parameter/python:
  - script: build
    dependencies:
      - clients/api/python:build
      - clients/soa/python:build
  - script: lint
    dependencies:
      - clients/soa_services/message/python:build
    tags:
      - test
  - script: test
    dependencies:
      - clients/api/python:test
      - clients/soa/python:test
      - clients/soa_services/message/python:build
      - clients/soa_services/message/python:lint
      - helper/python-test-helper:test
    tags:
      - test

clients/soa_services/parameter/js:
  - script: build
    dependencies:
      - clients/soa/js:build
  - script: lint
    dependencies:
      - clients/soa_services/message/js:build
    tags:
      - test

################################################################################
# Integration Tests ############################################################
################################################################################

integration-test:
  - script: test
    dependencies:
      - services/common:build
      - services/auth:build
      - services/authorization:build
      - services/booking/src/booking-backend:build
      - services/booking/src/booking-frontend:build
      - services/booking/src/device-reservation:build
      - services/booking/src/schedule-service:build
      - services/device:build
      - services/experiment:build
      - services/federation:build
      - services/gateway:build
      - services/auth:build-docker
      - services/authorization:build-docker
      - services/booking/src/booking-backend:build-docker
      - services/booking/src/booking-frontend:build-docker
      - services/booking/src/device-reservation:build-docker
      - services/booking/src/schedule-service:build-docker
      - services/device:build-docker
      - services/experiment:build-docker
      - services/federation:build-docker
      - services/gateway:build-docker
      - services/auth:test
      - services/authorization:test
      - clients/api/js:build
      - clients/soa/js:build
      - clients/soa_services/electricalConnection/js:build
      - helper/dummy-device/js:build
      - helper/dummy-device/python:build
    tags:
      - test
  - script: lint
    dependencies:
      - integration-test:test
    tags:
      - test