# This docker compose file is used to deploy the "core"-services of a Crosslab instance.
# This includes all services to provide the crosslab API. Any additional software like frontend,
# virtual laboratory devices etc. must be deployed on top of this.
#
# All necessary confifguration Options are set via environment variables in the accompanying .env file.
#
version: '3'

x-config: &common-config
  AUTHORIZATION_SERVER: 'http://127.0.0.1:3010'
  AUTHORIZATION_PSK: '${AUTHORIZATION_PSK:-TestPSK}'
  LOGGING: '${LOGGING:-info}'
  AUTH_SERVICE_URL: 'http://127.0.0.1:3000'
  DEVICE_SERVICE_URL: 'http://127.0.0.1:3001'
  EXPERIMENT_SERVICE_URL: 'http://127.0.0.1:3002'
  FEDERATION_SERVICE_URL: 'http://127.0.0.1:3003'
  BOOKING_SERVICE_URL: 'http://127.0.0.1:3004'
  FORWARDING_SERVICE_URL: 'http://127.0.0.1:3005'
  LTI_SERVICE_URL: 'http://127.0.0.1:3006'
  BASE_URL: 'http://localhost'

services:
  # Database
  db:
    image: mariadb:11.2.3
    network_mode: 'host'
    volumes:
      - './config/mariadb:/docker-entrypoint-initdb.d:ro'
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:?}
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--su=mysql', '--connect', '--innodb_initialized']
      interval: 3s
    restart: on-failure
  gateway:
    image: ${GATEWAY_IMAGE:?}
    ports:
      - '${API_PORT}:80'
    environment:
      <<: *common-config
      SERVER_NAME: 'localhost'
      AUTH_SERVICE_DOMAIN: '127.0.0.1:3000'
      DEVICE_SERVICE_DOMAIN: '127.0.0.1:3001'
      EXPERIMENT_SERVICE_DOMAIN: '127.0.0.1:3002'
      FEDERATION_SERVICE_DOMAIN: '127.0.0.1:3003'
      BOOKING_SERVICE_DOMAIN: '127.0.0.1:3004'
      FORWARDING_SERVICE_DOMAIN: '127.0.0.1:3005'
      AUTHORIZATION_SERVICE_DOMAIN: '127.0.0.1:3010'
      FORWARDING_SERVICE_DOMAIN: '127.0.0.1:3020'
      LTI_SERVICE_DOMAIN: '127.0.0.2:3006'
    network_mode: 'host'
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  # Services
  authentication:
    image: ${AUTHENTICATION_IMAGE:?}
    environment:
      <<: *common-config
      DB_USERNAME: authentication
      DB_DATABASE: authentication
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:?}
      JWT_SECRET: ${JWT_SECRET:?}
    network_mode: 'host'
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  authorization:
    image: ${AUTHORIZATION_IMAGE:?}
    environment:
      <<: *common-config
      DB_USERNAME: authorization
      DB_DATABASE: authorization
      JWT_SECRET: ${JWT_SECRET:?}
    network_mode: 'host'
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  booking:
    image: ${BOOKING_IMAGE:?}
    environment:
      <<: *common-config
      DB_USERNAME: booking
      DB_DATABASE: booking
    network_mode: 'host'
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  device:
    image: ${DEVICE_IMAGE:?}
    environment:
      <<: *common-config
      DB_USERNAME: device
      DB_DATABASE: device
    network_mode: 'host'
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  experiment:
    image: '${EXPERIMENT_IMAGE:?}'
    environment:
      <<: *common-config
      STUN_SERVER_URL: 'stun:stun.goldi-labs.de:3478'
      TURN_SERVER_URL: 'turn:turn.goldi-labs.de:3478'
      TURN_SERVER_USERNAME: 'goldi'
      TURN_SERVER_CREDENTIAL: 'goldi'
    network_mode: 'host'
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  federation:
    image: ${FEDERATION_IMAGE:?}
    environment:
      <<: *common-config
      DB_USERNAME: federation
      DB_DATABASE: federation
    network_mode: 'host'
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  forwarding:
    image: '${FORWARDING_IMAGE}'
    environment: *common-config
    network_mode: 'host'
