# This docker compose file is used to deploy the "core"-services of a Crosslab instance.
# This includes all services to provide the crosslab API. Any additional software like frontend,
# virtual laboratory devices etc. must be deployed on top of this.
#
# All necessary confifguration Options are set via environment variables in the accompanying .env file.
#
version: '3'

x-config: &common-config
  AUTHORIZATION_SERVER: 'http://localhost:3010'
  AUTHORIZATION_PSK: '${AUTHORIZATION_PSK:?}'
  LOGGING: '${LOGGING_LEVEL:-warn}'
  BASE_URL: ${API_BASE_URL}
  DB_TYPE: mariadb
  DB_HOST: localhost
  DB_PORT: 3306
  AUTH_SERVICE_URL: 'http://localhost:3000'
  DEVICE_SERVICE_URL: 'http://localhost:3001'
  EXPERIMENT_SERVICE_URL: 'http://localhost:3002'
  FEDERATION_SERVICE_URL: 'http://localhost:3003'
  BOOKING_FRONTEND_URL: 'http://localhost:3004'
  BOOKING_BACKEND_URL: 'http://localhost:3005'
  SCHEDULE_SERVICE_URL: 'http://localhost:3006'
  AUTH_SERVICE_DOMAIN: 'localhost:3000'
  DEVICE_SERVICE_DOMAIN: 'localhost:3001'
  EXPERIMENT_SERVICE_DOMAIN: 'localhost:3002'
  FEDERATION_SERVICE_DOMAIN: 'localhost:3003'
  BOOKING_FRONTEND_DOMAIN: 'localhost:3004'
  BOOKING_BACKEND_DOMAIN: 'localhost:3005'
  SCHEDULE_SERVICE_DOMAIN: 'localhost:3006'
  AUTHORIZATION_SERVICE_DOMAIN: 'localhost:3010'

services:
  # Database
  db:
    image: mariadb:11.2.3
    network_mode: 'host'
    volumes:
      - './config/mariadb:/docker-entrypoint-initdb.d:ro'
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:?}
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--su=mysql', '--connect', '--innodb_initialized']
    restart: on-failure
  rabbitmq:
    image: rabbitmq:3.13.4
    volumes:
      - ./config/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./config/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./config/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
    network_mode: 'host'
  gateway:
    image: ${GATEWAY_IMAGE:?}
    ports:
      - '${API_PORT}:80'
    environment:
      <<: *common-config
    network_mode: 'host'
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  # Services
  authentication:
    image: ${AUTHENTICATION_IMAGE:?}
    environment:
      <<: *common-config
      DB_USERNAME: authentication
      DB_DATABASE: authentication
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:?}
      JWT_SECRET: ${JWT_SECRET:?}
    network_mode: 'host'
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  authorization:
    image: ${AUTHORIZATION_IMAGE:?}
    environment:
      <<: *common-config
      DB_USERNAME: authorization
      DB_DATABASE: authorization
      JWT_SECRET: ${JWT_SECRET:?}
    network_mode: 'host'
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  booking-frontend:
    image: ${BOOKING_FRONTEND_IMAGE:?}
    environment:
      <<: *common-config
      BOOKING_DSN: mysql://booking@localhost:3306/booking?supportBigNumbers=true&bigNumberStrings=true
      AMQP_URL: amqp://rabbitmq:${RABBITMQ_PASSWORD:?}@localhost:5672
    network_mode: 'host'
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure
  booking-backend:
    image: ${BOOKING_BACKEND_IMAGE:?}
    environment:
      <<: *common-config
      BOOKING_DSN: mysql://booking@localhost:3306/booking?supportBigNumbers=true&bigNumberStrings=true
      AMQP_URL: amqp://rabbitmq:${RABBITMQ_PASSWORD:?}@localhost:5672
    network_mode: 'host'
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure
  schedule-service:
    image: ${SCHEDULE_SERVICE_IMAGE:?}
    environment:
      <<: *common-config
      BOOKING_DSN: mysql://booking@localhost:3306/booking?supportBigNumbers=true&bigNumberStrings=true
    network_mode: 'host'
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  device-reservation:
    image: ${DEVICE_RESERVATION_IMAGE:?}
    environment:
      <<: *common-config
      BOOKING_DSN: mysql://booking@localhost:3306/booking?supportBigNumbers=true&bigNumberStrings=true
      AMQP_URL: amqp://rabbitmq:${RABBITMQ_PASSWORD:?}@localhost:5672
    network_mode: 'host'
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: on-failure
  device:
    image: ${DEVICE_IMAGE:?}
    environment:
      <<: *common-config
      DB_USERNAME: device
      DB_DATABASE: device
    network_mode: 'host'
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  experiment:
    image: ${EXPERIMENT_IMAGE:?}
    environment:
      <<: *common-config
      DB_USERNAME: experiment
      DB_DATABASE: experiment
    network_mode: 'host'
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  federation:
    image: ${FEDERATION_IMAGE:?}
    environment:
      <<: *common-config
      DB_USERNAME: federation
      DB_DATABASE: federation
    network_mode: 'host'
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
