// tslint:disable
// @ts-nocheck
/**
 * This file was automatically generated by openapi-codegeneration.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source OpenAPI file,
 * and run openapi-codegeneration to regenerate this file.
 */
export async function getInstitutions() {
    // add your implementation here

    return {
        status: 200,
        data: "getInstitutions ok!",
    }
}

export async function postInstitutions() {
    // add your implementation here

    return {
        status: 200,
        data: "postInstitutions ok!",
    }
}

export async function getInstitutionsByInstitutionId() {
    // add your implementation here

    return {
        status: 200,
        data: "getInstitutionsByInstitutionId ok!",
    }
}

export async function patchInstitutionsByInstitutionId() {
    // add your implementation here

    return {
        status: 200,
        data: "patchInstitutionsByInstitutionId ok!",
    }
}

export async function deleteInstitutionsByInstitutionId() {
    // add your implementation here

    return {
        status: 200,
        data: "deleteInstitutionsByInstitutionId ok!",
    }
}
