# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.1/schema.json
openapi: 3.1.0
components:
  parameters:
    resource_id:
      name: resource_id
      in: path
      required: true
      schema:
        type: string
      description: The ID of the resource.
    student_id:
      name: student_id
      in: path
      required: true
      schema:
        type: string
      description: The ID of the student.
paths:
  resource:
    get:
      operationId: list_resource
      tags:
        - lti
      security:
        - JWT: []
      responses:
        '200':
          description: |-
            List all LTI-Resources.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../schemas/resource.yml'
        401:
          description: Unauthorized.
  resource_by_id:
    get:
      operationId: get_resource
      tags:
        - lti
      security:
        - JWT: []
      parameters:
        - $ref: '#/components/parameters/resource_id'
      responses:
        '200':
          description: |-
            Returns the resource.
          content:
            application/json:
              schema:
                $ref: '../schemas/resource.yml'
        401:
          description: Unauthorized.
    patch:
      operationId: update_resource
      tags:
        - lti
      security:
        - JWT: []
      parameters:
        - $ref: '#/components/parameters/resource_id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schemas/resource.yml#/$defs/partial'
      responses:
        '200':
          description: |-
            resource updated
          content:
            application/json:
              schema:
                $ref: '../schemas/resource.yml'
        400:
          description: Bad request
        401:
          description: Unauthorized.
    delete:
      operationId: delete_resource
      tags:
        - lti
      security:
        - JWT: []
      parameters:
        - $ref: '#/components/parameters/resource_id'
      responses:
        '204':
          description: |-
            resource deleted
        401:
          description: Unauthorized.
  resource_by_id_students:
    get:
      operationId: list_resource_students
      tags:
        - lti
      security:
        - JWT: []
      parameters:
        - $ref: '#/components/parameters/resource_id'
      responses:
        '200':
          description: |-
            List all students of the resource.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../schemas/student.yml'
        401:
          description: Unauthorized.
    patch:
      operationId: update_resource_students
      description: Update the students of the resource. Acts as you would call a PATCH on each student.
      tags:
        - lti
      security:
        - JWT: []
      parameters:
        - $ref: '#/components/parameters/resource_id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  uri:
                    type: string
                    format: uri
                  data:
                    $ref: '../schemas/student.yml'
                required:
                  - uri
                  - data
      responses:
        '200':
          description: |-
            Returns the students.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../schemas/student.yml'
        401:
          description: Unauthorized.
  resource_by_id_students_by_id:
    get:
      operationId: get_resource_student
      tags:
        - lti
      security:
        - JWT: []
      parameters:
        - $ref: '#/components/parameters/resource_id'
        - name: student_id
          in: path
          required: true
          schema:
            type: string
          description: The ID of the student.
      responses:
        '200':
          description: |-
            Returns the student.
          content:
            application/json:
              schema:
                $ref: '../schemas/student.yml'
        401:
          description: Unauthorized.
    patch:
      operationId: update_resource_student
      tags:
        - lti
      security:
        - JWT: []
      parameters:
        - $ref: '#/components/parameters/resource_id'
        - $ref: '#/components/parameters/student_id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '../schemas/student.yml'
      responses:
        '200':
          description: |-
            Returns the student.
          content:
            application/json:
              schema:
                $ref: '../schemas/student.yml'
        401:
          description: Unauthorized.
