# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.1/schema.json
openapi: 3.1.0
components:
  parameters:
    session_id:
      name: session_id
      in: path
      required: true
      schema:
        type: string
      description: The ID of the session.
paths:
  session:
    get:
      operationId: list_session
      tags:
        - lti
      security:
        - JWT: []
      responses:
        '200':
          description: |-
            List all LTI-Sessions.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../schemas/session.yml'
        401:
          description: Unauthorized.
  session_by_id:
    get:
      operationId: get_session
      tags:
        - lti
      security:
        - JWT: []
      parameters:
        - $ref: '#/components/parameters/session_id'
      responses:
        '200':
          description: |-
            Returns the session.
          content:
            application/json:
              schema:
                $ref: '../schemas/session.yml'
        401:
          description: Unauthorized.
    delete:
      operationId: delete_session
      tags:
        - lti
      security:
        - JWT: []
      parameters:
        - $ref: '#/components/parameters/session_id'
      responses:
        '204':
          description: |-
            session deleted
        401:
          description: Unauthorized.
  session_by_id_experiment:
    patch:
      summary: Update the LTI experiment settings.
      operationId: update_lti_experiment
      tags:
        - lti
      security:
        - JWT: []
      parameters:
        - $ref: '#/components/parameters/session_id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                impersonate:
                  description: URI of the student to impersonate.
                  type: string
                  format: uri
                role_mapping:
                  description: |-
                    Mapping of roles to devices.
                    This overwrites any existing role mapping possibles et by the student impersonation.
                  type: array
                  items:
                    type: object
                    properties:
                      role:
                        type: string
                      device:
                        anyOf:
                          - type: string
                            enum:
                              - GROUP
                          - type: string
                            format: uri
                            description: The URI of the device to use instead of the group device.
                    required:
                      - role
                      - device
      responses:
        201:
          description: |-
            The session was updated.
