// tslint:disable
// @ts-nocheck
/**
 * This file was automatically generated by openapi-codegeneration.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source OpenAPI file,
 * and run openapi-codegeneration to regenerate this file.
 */
import express from "express"
import bodyParser from "body-parser"
import institutions from "./routes/institutions"
import * as proxy from "./routes/proxy"
import {initServiceOptions} from "./types"

export const app: express.Application & {initService: (option: initServiceOptions)=>void} = express() as any

app.initService = (options) => {

    app.use(bodyParser.json())
    app.use(bodyParser.urlencoded({ extended: false }))
    
    /*
    * Routes
    */
   app.use("/institutions", institutions(options))
   app.use("/proxy", proxy.router)

   // catch 404
   app.use((req, res, next) => {
       console.error(`Error 404 on ${req.url}.`)
       res.status(404).send({ status: 404, error: "Not found" })
    })
    
    // catch errors
    app.use((err, req, res, next) => {
        const status = err.status || 500
        const msg = err.error || err.message
        console.error(
            `Error ${status} (${msg}) on ${req.method} ${req.url} with payload ${req.body}.`
        )
        res.status(status).send({ status, error: msg })
    })
}
