// tslint:disable
// @ts-nocheck
/**
 * This file was automatically generated by openapi-codegeneration.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source OpenAPI file,
 * and run openapi-codegeneration to regenerate this file.
 */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type initServiceOptions = {
    JWTVerify: (jwt: string, endpoint_scopes: [string])=>unknown
}

export interface Institution {
    name?: string
    homepage?: string
    api?: string
    federatedApi?: string
    apiToken?: string
    [k: string]: unknown
}