version: "3"

# docker plugin install grafana/loki-docker-driver:2.8.2 --alias loki --grant-all-permissions

x-loki: &loki-logging
  driver: loki
  options:
    loki-url: http://localhost:3100/loki/api/v1/push
    loki-external-labels: project=crosslab
    loki-pipeline-stages: |
      - regex:
          expression: '"(level)":"(?P<level>\w+)"'
      - labels:
          level:
    loki-relabel-config: |
      - action: labelmap
        regex: compose_(service)
      - action: labelkeep
        regex: (service|project)
    labels: level,service
  
x-config: &common-config
  AUTHORIZATION_SERVER: "127.0.0.1:3010"
  AUTHORIZATION_PSK: "${AUTHORIZATION_PSK:-please change me}"
  LOGGING: "${LOGGING:-info}"

services:
  # Logging
  loki:
    image: grafana/loki:2.8.3
    command: -config.file=/etc/loki/local-config.yaml
    network_mode: "host"
  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SERVER_HTTP_PORT=3101
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/ds.yaml
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    image: grafana/grafana:latest
    network_mode: "host"
  # Services
  gateway:
    build: ../../../services/gateway
    environment:
      <<: *common-config
      AUTH_SERVICE_URL: "127.0.0.1:3000"
      DEVICE_SERVICE_URL: "127.0.0.1:3001"
      EXPERIMENT_SERVICE_URL: "127.0.0.1:3002"
      FEDERATION_SERVICE_URL: "127.0.0.1:3003"
      UPDATE_SERVICE_URL: "127.0.0.1:1"
      SERVER_NAME: "localhost"
    network_mode: "host"
    logging: *loki-logging
  authentication:
    build: ../../../services/auth
    environment: *common-config
    network_mode: "host"
    logging: *loki-logging
  authorization:
    build: ../../../services/authorization
    environment: *common-config
    network_mode: "host"
    logging: *loki-logging
  device:
    build: ../../../services/device
    environment: *common-config
    network_mode: "host"
    logging: *loki-logging
  experiment:
    build: ../../../services/experiment
    environment: *common-config
    network_mode: "host"
    logging: *loki-logging
  federation:
    build: ../../../services/federation
    environment: *common-config
    network_mode: "host"
    logging: *loki-logging
