# yaml-language-server: $schema=https://json-schema.org/draft/2020-12/schema
title: Configured Device Reference
type: object
properties:
  url:
    type: string
    description: URL of the device
    format: uri
  config:
    type: object
    properties:
      services:
        type: array
        items:
          $ref: '../services/service_config.yml'
required:
  - url