# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.1/schema.json
openapi: 3.1.0
info:
  title: CrossLab REST API
  description: |-
    This is the OpenAPI description for the CrossLab REST API.
  version: 0.0.1

servers:
  - url: 'https://{tenant}'
    variables:
      tenant:
        default: 'api.cross-lab.org'
        description: The tenant name of the CrossLab instance.

components:
  securitySchemes:
    default:
      type: http
      scheme: basic

paths:
  $ref: './gen/paths.json'