// tslint:disable
// @ts-nocheck
/**
 * This file was automatically generated by openapi-codegeneration.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source OpenAPI file,
 * and run openapi-codegeneration to regenerate this file.
 */
import {} from "../types"
import { validateParameterSchemaURL } from "./validation"

export function validateInputGetProxy(parameters: { URL: string }) {
    if (parameters) {
        if (!validateParameterSchemaURL(parameters.URL)) return false
    }

    return true
}

export function validateInputPostProxy(parameters: { URL: string }) {
    if (parameters) {
        if (!validateParameterSchemaURL(parameters.URL)) return false
    }

    return true
}

export function validateInputPatchProxy(parameters: { URL: string }) {
    if (parameters) {
        if (!validateParameterSchemaURL(parameters.URL)) return false
    }

    return true
}

export function validateInputDeleteProxy(parameters: { URL: string }) {
    if (parameters) {
        if (!validateParameterSchemaURL(parameters.URL)) return false
    }

    return true
}

export function validateInputOptionsProxy(parameters: { URL: string }) {
    if (parameters) {
        if (!validateParameterSchemaURL(parameters.URL)) return false
    }

    return true
}

export function validateInputHeadProxy(parameters: { URL: string }) {
    if (parameters) {
        if (!validateParameterSchemaURL(parameters.URL)) return false
    }

    return true
}

export function validateInputTraceProxy(parameters: { URL: string }) {
    if (parameters) {
        if (!validateParameterSchemaURL(parameters.URL)) return false
    }

    return true
}

export function validateInputPutProxy(parameters: { URL: string }) {
    if (parameters) {
        if (!validateParameterSchemaURL(parameters.URL)) return false
    }

    return true
}
