# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.1/schema.json
openapi: 3.1.0
info:
  title: CrossLab Simple Authentication Service (internal)
  description: |-
    This is the OpenAPI description for a simple authentification server, supporting LDAP and Token based authentication.
  version: 0.0.1

servers:
  - url: https://api.goldi-labs.de/

components:
  securitySchemes:
    TuiAuth:
      type: http
      scheme: basic
      description: Basic authentication using the TUI username and password.
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |-
        As this is the API description of the internal Authentication API, the only supported security schema is the JWT bearer token.
        This token will be populated by the API Gateway.
        To learn about the general Authentification scheme, please refer to the [Authentication section](https://cross-lab-project.github.io/crosslab/backend.html#authentification) in the CrossLab architecture description.
paths:
  /auth:
    $ref: "./resources/auth.yml"
  /login:
    $ref: "./resources/login.yml"
  /users:
    $ref: "./resources/users.yml"
  /users/{username}:
    $ref: "./resources/user.yml"
  /users/{username}/roles/{role_name}:
    $ref: "./resources/user_role.yml"
  /identity:
    $ref: "./resources/identity.yml"