#!/usr/bin/bash

current=$(pwd)

rm -f dist/openapi.yml
echo "# This file was automatically generated by documentation-and-generation.fish - all changes will be lost\n" > dist/openapi.yml
echo "# This file was automatically generated by documentation-and-generation.fish - all changes will be lost\n" > src/schedule-service/dist/openapi.yml
echo "# This file was automatically generated by documentation-and-generation.fish - all changes will be lost\n" > src/booking-frontend/dist/openapi.yml
echo "# This file was automatically generated by documentation-and-generation.fish - all changes will be lost\n" > src/booking-backend/dist/openapi.yml

cat api/openapi_start.yml >> dist/openapi.yml
cat src/schedule-service/api/component.yml >> dist/openapi.yml
cat src/booking-frontend/api/component.yml >> dist/openapi.yml
cat src/booking-backend/api/component.yml >> dist/openapi.yml
cat api/types.yml >> dist/openapi.yml

cat src/schedule-service/api/openapi_start.yml >> src/schedule-service/dist/openapi.yml
cat src/schedule-service/api/component.yml >> src/schedule-service/dist/openapi.yml
cat api/types.yml >> src/schedule-service/dist/openapi.yml

cat src/booking-frontend/api/openapi_start.yml >> src/booking-frontend/dist/openapi.yml
cat src/booking-frontend/api/component.yml >> src/booking-frontend/dist/openapi.yml
cat api/types.yml >> src/booking-frontend/dist/openapi.yml

cat src/booking-backend/api/openapi_start.yml >> src/booking-backend/dist/openapi.yml
cat src/booking-backend/api/component.yml >> src/booking-backend/dist/openapi.yml
cat api/types.yml >> src/booking-backend/dist/openapi.yml

npx @redocly/cli bundle dist/openapi.yml --output dist/openapi.json

npx @redocly/cli bundle src/schedule-service/dist/openapi.yml --output src/schedule-service/dist/openapi.json
npx @redocly/cli bundle src/booking-frontend/dist/openapi.yml --output src/booking-frontend/dist/openapi.json
npx @redocly/cli bundle src/booking-backend/dist/openapi.yml --output src/booking-backend/dist/openapi.json

cd "$current/src/schedule-service"
npx openapi-codegen -i dist/openapi.json -p @cross-lab-project/codegen-typescript-addon:preset:service -o src/generated
cd "$current/src/booking-frontend"
npx openapi-codegen -i dist/openapi.json -p @cross-lab-project/codegen-typescript-addon:preset:service -o src/generated
cd "$current/src/booking-backend"
npx openapi-codegen -i dist/openapi.json -p @cross-lab-project/codegen-typescript-addon:preset:service -o src/generated

cd $current
