openapi: 3.0.1
info:
  title: Booking service
  description: All APIs (public and private) provided by the booking service
  version: 0.0.0
servers:
  - url: /v0
tags:
  - name: public
    description: Public APIs accessable by everyone (as long as authorised)
  - name: private
    description: Internal APIs needed for inter-institutional operations. Only available to other booking systems.
paths:
  /booking/schedule:
    post:
      tags:
        - public
      summary: Returns the free / booked times for given experiment.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
               - Experiment
               - Start
               - End
              properties:
                Experiment:
                  $ref: '#/components/schemas/Experiment'
                Start:
                  type: string
                  format: RFC3339
                  description: Start time for the booking.
                End:
                  type: string
                  format: RFC3339
                  description: End time for the booking.
                Combined:
                  type: boolean
      responses:
        '200':
          description: Timetable of free/booked time. If 'Combined' is set to true, an array with only one entry is returned containing the combined timetable.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                   - Device
                   - Booked
                   - Free
                  properties:
                    Device:
                      type: string
                      description: ID of the device (or * if combined).
                    Booked:
                      type: array
                      description: Array of booked times.
                      items:
                        $ref: '#/components/schemas/Timeslot'
                    Free:
                      type: array
                      description: Array of free times.
                      items:
                        $ref: '#/components/schemas/Timeslot'
                   
        '401':
          description: No authorisation header found.
        '404':
          description: Request contains unknown type IDs. Those will be listed in response.
          content:
            application/json:
              schema:
                type: array
                description: List of unknown device IDs.
                items:
                  type: string
        '503':
          description: >-
            Request could not be answered. An error string containing the reason
            will be returned.
          content:
            application/json:
              schema:
                type: string
                description: Error description.
  /booking/manage:
    put:
      tags:
        - public
      summary: Books an experiment.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
               - Experiment
               - Start
               - End
              properties:
                Experiment:
                 $ref: '#/components/schemas/Experiment'
                Start:
                  type: string
                  description: Start time of the booking.
                  format: RFC3339
                End:
                  type: string
                  description: End time of the booking.
                  format: RFC3339
      responses:
        '200':
          description: All devices were booked successfully.
          content:
            application/json:
              schema:
                type: object
                required: 
                 - BookingID
                properties:
                  BookingID:
                    type: string
                    format: URI
                    description: ID at which the booking can be managed.
        '401':
          description: No authorisation header found.
        '404':
          description: Request contains unknown device IDs. Those will be listed in response.
          content:
            application/json:
              schema:
                type: array
                description: List of unknown device IDs.
                items:
                  type: string
        '409':
          description: >-
            One or multiple devices are not available. Those will be listed in
            response.
          content:
            application/json:
              schema:
                type: array
                description: List of unavailable device IDs.
                items:
                  type: string
        '503':
          description: >-
            Request could not be answered. An error string containing the reason
            will be returned.
          content:
            application/json:
              schema:
                description: Error description
                type: string
  /booking/manage/{ID}:
    patch:
      parameters:
        - in: path
          name: ID
          schema:
            type: string
          required: true
          description: ID of Booking
      tags:
        - public
      summary: Allows the addition of devices to a booking (removing of devices is not supportet) or the registration of callbacks.
      requestBody:
        content:
          application/json:
            schema:
              anyOf:
              -  type: object
                 description: Use this request for adding devices.
                 properties:
                    Locked:
                      type: boolean
                      description: Expresses whether the devices should be locked. Must match current status of booking.
                    Devices:
                     type: array
                     description: List of devices which should be added.
                     items: 
                      $ref: '#/components/schemas/Device'
                    Start:
                      type: string
                      description: Start time of the booking.
                      format: RFC3339
                    End:
                      type: string
                      description: End time of the booking.
                      format: RFC3339
              - type: object
                description: Use this request for adding callbacks.
                properties:
                  Callback:
                    type: string
                    format: URI
                    description: Callback which should be called at changes.
        required: true
      responses:
        '200':
          description: All devices were booked successfully.
          content:
            application/json:
              schema:
                type: object
                required:
                  - BookingID
                properties:
                  BookingID:
                    type: string
                    format: URI
                  Token:
                    type: array
                    description: If the booking is locked, a list of access tokens will be send. If booking is not locked, this will not be returned in response.
                    items:
                      type: string
        '401':
          description: No authorisation header found.
        '404':
          description: Request contains unknown device IDs. Those will be listed in response.
          content:
            application/json:
              schema:
                type: array
                description: List of unknown device IDs.
                items:
                  type: string
        '409':
          description: >-
            One or multiple devices are not available. Those will be listed in
            response.
          content:
            application/json:
              schema:
                type: array
                description: List of unavailable devices.
                items:
                  type: string
        '423': 
          description: >-
            The booking 'locked' status and the requested locked status do not match.
        '503':
          description: >-
            Request could not be answered. An error string containing the reason
            will be returned.
          content:
            application/json:
              schema:
                type: string
                description: Error description
    delete:
      parameters:
        - in: path
          name: ID
          schema:
            type: string
          required: true
          description: ID of Booking
      tags:
        - public
      summary: Cancels a booking
      responses:
        '200':
          description: >-
            The booking was cancelled. All associated devices were released.
        '401':
          description: No authorisation header found.
        '404':
          description: Request contains unknown booking ID.
        '423':
          description: >-
            Some of the devices are currently in use, no device booking is cancelled. The locked
            devices are listed in response.
          content:
            application/json:
              schema:
                type: array
                description: List of locked devices.
                items:
                  type: string
        '503':
          description: >-
            Request could not be answered. An error string containing the reason
            will be returned.
          content:
            application/json:
              schema:
                type: string
                description: Error description
    get:
      parameters:
        - in: path
          name: ID
          schema:
            type: string
          required: true
          description: ID of Booking
      tags:
      - public
      summary: >-
        Returns whether a list of devices is currently booked for a user
      responses:
        '200':
          description: All devices were booked by user.
          content:
            application/json:
              schema:
                type: object
                properties:
                  Experiment:
                    $ref: '#/components/schemas/Experiment'
                  Bookings:
                    type: array
                    items:
                      $ref: '#/components/schemas/Booking'
                  Start:
                    type: string
                    description: Start time of booking.
                    format: RFC3339
                  End:
                    type: string
                    format: RFC3339
                    description: End time of booking.
        '401':
          description: No authorisation header found.
        '404':
          description: Request contains unknown ID
        '503':
          description: >-
            Request could not be answered. An error string containing the reason
            will be returned.
          content:
            application/json:
              schema:
                type: string
                description: Error code
  /booking/lock/{ID}:
    put:
      parameters:
        - in: path
          name: ID
          schema:
            type: string
          required: true
          description: ID of Booking
      tags:
      - public
      summary: >-
        Locks all devices belonging to a booking. This means that the booking can not be cancelled or (currently not implemented) the end time can not be set to a prior time.
      responses:
        '200':
          description: All devices were booked by user.
          content:
            application/json:
              schema:
                type: object
                properties:
                  Bookings:
                    type: array
                    items:
                      $ref: '#/components/schemas/Booking'
                  Start:
                    type: string
                    format: RFC3339
                    description: Start time of booking
                  End:
                    type: string
                    format: RFC3339
                    description: End time of booking.
                  Token:
                    type: array
                    description: A list of access tokens
                    items:
                      type: string
        '401':
          description: No authorisation header found.
        '404':
          description: Request contains unknown ID
        '503':
          description: >-
            Request could not be answered. An error string containing the reason
            will be returned.
          content:
            application/json:
              schema:
                type: string
                description: Error string
    delete:
      parameters:
        - in: path
          name: ID
          schema:
            type: string
          required: true
          description: ID of Booking
      tags:
      - public
      summary: >-
        Unlocks all devices belonging to a booking
      responses:
        '200':
          description: All devices were booked by user.
          content:
            application/json:
              schema:
                type: object
                properties:
                  Bookings:
                    type: array
                    items:
                      $ref: '#/components/schemas/Booking'
                  Start:
                    type: string
                    format: RFC3339
                    description: Start time of deleted booking.
                  End:
                    type: string
                    format: RFC3339
                    description: End time of deleted booking.
        '401':
          description: No authorisation header found.
        '404':
          description: Request contains unknown ID
        '503':
          description: >-
            Request could not be answered. An error string containing the reason
            will be returned.
          content:
            application/json:
              schema:
                type: string
                description: Error description.


components:
  schemas:
    Booking:
      description: A booking in the booking system.
      type: object
      required:
       - ID
       - Time
       - Devices
       - You
      properties:
        ID:
          type: string
          format: URI
          description: Unique ID of the booking.
        Time:
          $ref: "#/components/schemas/Timeslot"
        Devices:
          type: array
          items:
            type: string
            format: URI
        You:
          type: boolean
          description: If true, this booking was done by you.
    Device:
      description: A device might either be a physical/virtual device or a group of device.
      type: object
      required:
       - ID
      properties:
        ID:
          type: string
          description: Unique ID of the device.
          format: URI
        Institute:
          type: string
          description: Institute at which the device is located.
    Experiment:
      description: An experiment describes a set of devices and how they should be connected (potentially among other metadata).
      type: object
      required:
       - Devices
      properties:
        Devices:
          type: array
          description: List of devices used in experiment.
          items:
            $ref: "#/components/schemas/Device"
    Timeslot:
      description: A time slot represents a slice of time used for bookings.
      type: object
      properties:
        Start:
          type: string
          description: Start time of the booking.
          format: RFC3339
        End:
          type: string
          description: End time of the booking.
          format: RFC3339
