{
  "openapi": "3.1.0",
  "info": {
    "title": "CrossLab Simple Authentication Service (internal)",
    "description": "This is the OpenAPI description for a simple authentification server, supporting LDAP and Token based authentication.",
    "version": "0.0.1"
  },
  "servers": [
    {
      "url": "https://api.goldi-labs.de"
    },
    {
      "url": "http://localhost"
    }
  ],
  "components": {
    "securitySchemes": {
      "TuiAuth": {
        "type": "http",
        "scheme": "basic",
        "description": "Basic authentication using the TUI username and password."
      },
      "JWT": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT",
        "description": "As this is the API description of the internal Authentication API, the only supported security schema is the JWT bearer token.\nThis token will be populated by the API Gateway.\nTo learn about the general Authentification scheme, please refer to the [Authentication section](https://cross-lab-project.github.io/crosslab/backend.html#authentification) in the CrossLab architecture description."
      }
    }
  },
  "paths": {
    "/auth": {
      "get": {
        "x-internal": true,
        "tags": [
          "authentication"
        ],
        "security": [
          {
            "AccessToken": []
          }
        ],
        "operationId": "auth",
        "summary": "Authenticate user",
        "description": "This endpoint will authenticate a user and return a JWT for the internal use of the microservice architecture.\nThe return code will always be 200, but the JWT will be empty if the authentication failed."
      }
    },
    "/login": {
      "post": {
        "tags": [
          "authentication"
        ],
        "operationId": "login",
        "summary": "Login user",
        "description": "This endpoint will login a user and return an access token for the use of the microservice architecture."
      }
    },
    "/logout": {
      "post": {
        "tags": [
          "authentication"
        ],
        "security": [
          {
            "JWT": [
              "logout"
            ]
          }
        ],
        "operationId": "logout",
        "summary": "Logout user",
        "description": "This endpoint will logout a user and remove the corresponding access token for the use of the microservice architecture."
      }
    },
    "/device_token": {
      "post": {
        "tags": [
          "authentication"
        ],
        "security": [
          {
            "JWT": [
              "device_token",
              "device_token:create"
            ]
          }
        ],
        "operationId": "device_token",
        "summary": "Authenticate user",
        "description": "This endpoint will generate a new device token linked to the requesting user."
      }
    },
    "/users": {
      "get": {
        "summary": "Get all users",
        "tags": [
          "user"
        ],
        "security": [
          {
            "JWT": [
              "users",
              "users:list"
            ]
          }
        ]
      },
      "post": {
        "summary": "Create new user",
        "tags": [
          "user"
        ],
        "security": [
          {
            "JWT": [
              "users",
              "users:create"
            ]
          }
        ]
      }
    },
    "/users/{username}": {
      "get": {
        "summary": "Get user by username",
        "tags": [
          "user"
        ],
        "security": [
          {
            "JWT": [
              "users",
              "users:list"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Update user by username",
        "tags": [
          "user"
        ],
        "security": [
          {
            "JWT": [
              "users",
              "users:edit"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete user by username",
        "tags": [
          "user"
        ],
        "security": [
          {
            "JWT": [
              "users",
              "users:create"
            ]
          }
        ]
      }
    },
    "/users/{username}/roles/{role_name}": {
      "put": {
        "summary": "Add new role to user",
        "tags": [
          "user"
        ],
        "security": [
          {
            "JWT": [
              "users",
              "users:edit"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete role from user",
        "tags": [
          "user"
        ],
        "security": [
          {
            "JWT": [
              "users",
              "users:edit"
            ]
          }
        ]
      }
    },
    "/identity": {
      "get": {
        "summary": "Get identity of yourself",
        "tags": [
          "identity"
        ],
        "security": [
          {
            "JWT": [
              "identity",
              "identity:list"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Update identity of yourself",
        "tags": [
          "identity"
        ],
        "security": [
          {
            "JWT": [
              "identity",
              "identity:edit"
            ]
          }
        ]
      }
    }
  }
}