{
 "title": "Log Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "requestID",
    "label": "Request Id",
    "query": "c90ecd1b03a9d423baf02d876b601291"
   }
  ]
 },
 "panels": [
  {
   "title": "Gateway Service",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{service=\"gateway\"} |= `requestID` |= `$requestID` | json | line_format `{{.requestID}} {{.request}} {{.status}} in {{.request_time}}`"
    },
    {
     "expr": "{service=\"gateway\"} != `requestID` |= `$requestID`"
    }
   ]
  },
  {
   "title": "Authentication Service",
   "type": "logs",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{service=\"authentication\"} |= `$requestID` | json | line_format `{{.message}}`"
    }
   ]
  },
  {
   "title": "Authentication Service",
   "type": "logs",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "{service=\"authentication\"} |= `$requestID` | json | line_format `{{.message}}`"
    }
   ]
  },
  {
   "title": "Device Service",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{service=\"device\"} |= `$requestID` |~ `^\\{` | json | line_format `{{.message}}`"
    },
    {
     "expr": "{service=\"device\"} |= `$requestID` !~ `^\\{`"
    }
   ]
  },
  {
   "title": "Federation Service",
   "type": "logs",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "{service=\"federation\"} |= `$requestID` | json | line_format `{{.message}}`"
    }
   ]
  },
  {
   "title": "Experiment Service",
   "type": "logs",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{service=\"experiment\"} |= `$requestID` | json | line_format `{{.message}}`"
    }
   ]
  },
  {
   "title": "Booking Service",
   "type": "logs",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "{service=\"authorization\"} |=\"$requestID\"  | json | line_format \"{{.message}}\" "
    }
   ]
  }
 ]
}