openapi: 3.1.0
info:
  title: booking-frontend single api
  description: >-
    workaround for openapi-codegen, who assumes a structure where every service has its own file.
  version: 1.0.0
  x-service-name: Booking Service
servers:
  - url: /v1
tags:
  - name: schedule-service
  - name: booking-frontend
  - name: booking-backend
  - name: device-reservation

paths:
