# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.1/schema.json
openapi: 3.1.0
info:
  title: CrossLab Device Service REST API (internal)
  description: |-
    This is the OpenAPI description of the internal CrossLab Device Service REST API.
  version: 0.0.1
  x-service-name: Device Service

components:
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |-
        As this is the API description of the internal Device API, the only supported security schema is the JWT bearer token.
        This token will be populated by the API Gateway.
        To learn about the general Authentification scheme, please refer to the [Authentication section](https://cross-lab-project.github.io/crosslab/backend.html#authentification) in the CrossLab architecture description.
  schemas:
    authentication_message:
      $ref: './schemas/messages/authentication_message.yml'
    connection_state_changed_message:
      $ref: './schemas/messages/connection_state_changed_message.yml'
tags:
  - name: device
    description: |-
      This tag describes the device resource.
  - name: peerconnection
    description: |-
      This tag describes the peer connection resource.
paths:
  /devices:
    $ref: './resources/devices.yml'
  /devices/{device_id}:
    $ref: './resources/device.yml'
  /devices/{device_id}/availability:
    $ref: './resources/device_availability.yml'
  /devices/{device_id}/websocket:
    $ref: './resources/websocket_token.yml'
  /devices/{device_id}/signaling:
    $ref: './resources/device_signaling.yml'
  /peerconnections:
    $ref: './resources/peerconnections.yml'
  /peerconnections/{peerconnection_id}:
    $ref: './resources/peerconnection.yml'
  /peerconnections/{peerconnection_id}/device_status:
    $ref: './resources/peerconnection_device_status.yml'
