#!/bin/bash

mkdir -p dist

rm -f dist/openapi.yml
echo "# This file was automatically generated by documentation-and-generation.fish - all changes will be lost\n" > dist/openapi.yml

cat api/openapi_start.yml >> dist/openapi.yml
cat api/component.yml >> dist/openapi.yml
cat api/types.yml >> dist/openapi.yml
cat ../../api/types.yml >> dist/openapi.yml

npx @redocly/cli bundle dist/openapi.yml --output dist/openapi.json
