location = /schedule {
    limit_except post { deny all; }
    auth_request @auth;
    auth_request_set $authentication $upstream_http_x_request_authentication;

    proxy_set_header X-Request-Authentication $authentication;
    proxy_set_header X-Request-ID $request_id;
    proxy_pass http://booking_service;
}

location = /bookings {
    limit_except post get { deny all; }
    auth_request @auth;
    auth_request_set $authentication $upstream_http_x_request_authentication;

    proxy_set_header X-Request-Authentication $authentication;
    proxy_set_header X-Request-ID $request_id;
    proxy_pass http://booking_service;
}

location ~ ^/bookings/[^/]+$ {
    limit_except get delete patch { deny all; }
    auth_request @auth;
    auth_request_set $authentication $upstream_http_x_request_authentication;

    proxy_set_header X-Request-Authentication $authentication;
    proxy_set_header X-Request-ID $request_id;
    proxy_pass http://booking_service;
}

location ~ ^/bookings/[^/]+/lock$ {
    limit_except put delete { deny all; }
    auth_request @auth;
    auth_request_set $authentication $upstream_http_x_request_authentication;

    proxy_set_header X-Request-Authentication $authentication;
    proxy_set_header X-Request-ID $request_id;
    proxy_pass http://booking_service;
}

location  = /callbacks/booking {
    limit_except post { deny all; }
    auth_request @auth;
    auth_request_set $authentication $upstream_http_x_request_authentication;

    proxy_set_header X-Request-Authentication $authentication;
    proxy_set_header X-Request-ID $request_id;
    proxy_pass http://booking_service;
}