location = /forwarding/status {
    limit_except get options { deny all; }

    proxy_pass http://forwarding_service;
}

location ~ ^/rooms/[^/]+$ {
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
    proxy_pass http://forwarding_service;
}