# yaml-language-server: $schema=https://json-schema.org/draft/2020-12/schema
title: Service Config
type: object
properties:
    serviceType:
        type: string
        format: uri
    serviceId:
        type: string
    remoteServiceId:
        type: string
required:
    - serviceType
    - serviceId
    - remoteServiceId
additionalProperties: true
