# yaml-language-server: $schema=https://json-schema.org/draft/2020-12/schema
title: Upstream Signal Interface Configuration
description: Configuration for a signal interface
allOf:
  - $ref: ../schemas/signal_interface_configuration.yml
  - type: object
    properties:
        interfaceType:
          type: string
        interfaceId:
          type: string
        busId:
          type: string
    required:
      - interfaceType
      - interfaceId
      - busId