---
version: '2'
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: bridge

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=$EMAIL
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge

  gateway:
    image: crosslab/gateway-service
    environment:
      - VIRTUAL_HOST=api.$DOMAIN
      - VIRTUAL_PORT=80
      - SERVER_NAME=api.$DOMAIN
      - DEVICE_SERVICE_URL=device:8080
      - EXPERIMENT_SERVICE_URL=experiment:8080
      - FEDERATION_SERVICE_URL=federation:8080
      - LOGS_SERVICE_URL=logs:8080
      - AUTH_SERVICE_URL=auth:8080
  auth:
    image: crosslab/auth-service
    environment:
      SECURITY_ISSUER: https://dev.goldi-labs.de
      SECURITY_AUDIENCE: https://dev.goldi-labs.de
  device:
    image: crosslab/device-service
    environment:
      SECURITY_ISSUER: https://dev.goldi-labs.de
      SECURITY_AUDIENCE: https://dev.goldi-labs.de
  experiment:
    image: crosslab/experiment-service
    environment:
      SECURITY_ISSUER: https://dev.goldi-labs.de
      SECURITY_AUDIENCE: https://dev.goldi-labs.de
  federation:
    image: crosslab/federation-service
    environment:
      SECURITY_ISSUER: https://dev.goldi-labs.de
      SECURITY_AUDIENCE: https://dev.goldi-labs.de
  

  logs:
    image: amir20/dozzle
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      DOZZLE_BASE: /logs

volumes:
  conf:
  vhost:
  html:
  certs:
  acme: