---
version: '2'
services:

# Reverse Proxy ###################################################################################
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=$EMAIL
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro

# API #############################################################################################
  gateway:
    image: crosslab/gateway-service
    environment:
      - VIRTUAL_HOST=api.$DOMAIN
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=api.$DOMAIN
      - SERVER_NAME=api.$DOMAIN
      - DEVICE_SERVICE_URL=device:8080
      - EXPERIMENT_SERVICE_URL=experiment:8080
      - FEDERATION_SERVICE_URL=federation:8080
      - LOGS_SERVICE_URL=logs:8080
      - AUTH_SERVICE_URL=auth:8080
  auth:
    image: crosslab/auth-service
    environment:
      SECURITY_ISSUER: https://$DOMAIN
      SECURITY_AUDIENCE: https://$DOMAIN
  device:
    image: crosslab/device-service
    environment:
      SECURITY_ISSUER: https://$DOMAIN
      SECURITY_AUDIENCE: https://$DOMAIN
  experiment:
    image: crosslab/experiment-service
    environment:
      SECURITY_ISSUER: https://$DOMAIN
      SECURITY_AUDIENCE: https://$DOMAIN
  federation:
    image: crosslab/federation-service
    environment:
      SECURITY_ISSUER: https://$DOMAIN
      SECURITY_AUDIENCE: https://$DOMAIN
  
# Frontend ########################################################################################
  frontend:
    image: goldi2/web-frontend
    environment:
      - VIRTUAL_HOST=www.$DOMAIN
      - VIRTUAL_PORT=8080
      - VIRTUAL_PATH=/
      - LETSENCRYPT_HOST=www.$DOMAIN
  gift:
    image: goldi2/gift
    environment:
      - VIRTUAL_HOST=www.$DOMAIN
      - VIRTUAL_PORT=80
      - VIRTUAL_PATH=/gift
      - VIRTUAL_DEST=/
      - LETSENCRYPT_HOST=www.$DOMAIN

  sane:
    image: goldi2/sane
    environment:
      - VIRTUAL_HOST=www.$DOMAIN
      - VIRTUAL_PORT=80
      - VIRTUAL_PATH=/SANE
      - VIRTUAL_DEST=/
      - LETSENCRYPT_HOST=www.$DOMAIN
      - BASE_PATH=/SANE/
  
# Logging #########################################################################################
  logs:
    image: amir20/dozzle
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - VIRTUAL_HOST=logs.$DOMAIN
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=logs.$DOMAIN
      - DOZZLE_USERNAME=$DOZZLE_USERNAME
      - DOZZLE_PASSWORD=$DOZZLE_PASSWORD

volumes:
  conf:
  vhost:
  html:
  certs:
  acme: