---
version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      crosslab:
        aliases:
          - "api.localhost"
  gateway:
    image: crosslab/gateway-service-dev
    environment:
      - VIRTUAL_HOST=api.localhost
      - VIRTUAL_PORT=80
      # - LETSENCRYPT_HOST=localhost
      - SERVER_NAME=api.localhost
      - DEVICE_SERVICE_URL=device:8080
      - EXPERIMENT_SERVICE_URL=experiment:8080
      - FEDERATION_SERVICE_URL=federation:8080
      - LOGS_SERVICE_URL=logs:8080
      - AUTH_SERVICE_URL=auth:8080
      - UPDATE_SERVICE_URL=update:8080
    networks:
      crosslab:
    depends_on:
      - auth
      - device
      - experiment
      - federation
      - update
  auth:
    image: crosslab/auth-service-dev
    command: dumb-init npm run dev
    environment:
      SECURITY_ISSUER: https://localhost
      SECURITY_AUDIENCE: https://localhost
      BASE_URL: http://api.localhost
      WHITELISTED: auth,device,experiment,federation,update
    volumes:
      - auth_service_node_modules_dev:/app/node_modules
      - auth_service_database_dev:/app/db
      - ../../../services/auth:/app
    networks:
      crosslab:
  device:
    image: crosslab/device-service-dev
    command: dumb-init npm run dev
    environment:
      SECURITY_ISSUER: https://localhost
      SECURITY_AUDIENCE: https://localhost
      BASE_URL: http://api.localhost
    volumes:
      - device_service_node_modules_dev:/app/node_modules
      - device_service_database_dev:/app/db
      - ../../../services/device:/app
    networks:
      crosslab:
  experiment:
    image: crosslab/experiment-service-dev
    command: dumb-init npm run dev
    environment:
      SECURITY_ISSUER: https://localhost
      SECURITY_AUDIENCE: https://localhost
      BASE_URL: http://api.localhost
    volumes:
      - experiment_service_node_modules_dev:/app/node_modules
      - experiment_service_database_dev:/app/db
      - ../../../services/experiment:/app
    networks:
      crosslab:
  federation:
    image: crosslab/federation-service-dev
    command: dumb-init npm run dev
    environment:
      SECURITY_ISSUER: https://localhost
      SECURITY_AUDIENCE: https://localhost
      BASE_URL: http://api.localhost
    volumes:
      - federation_service_node_modules_dev:/app/node_modules
      - federation_service_database_dev:/app/db
      - ../../../services/federation:/app
    networks:
      crosslab:
  update:
    image: crosslab/update-service-dev
    command: dumb-init npm run dev
    environment:
      SECURITY_ISSUER: https://localhost
      SECURITY_AUDIENCE: https://localhost
      BASE_URL: http://api.localhost
    volumes:
      - update_service_node_modules_dev:/app/node_modules
      - update_service_database_dev:/app/db
      - ../../../services/update:/app
    networks:
      crosslab:
  logs:
    image: amir20/dozzle
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - VIRTUAL_HOST=logs.localhost
      - VIRTUAL_PORT=8080
      # - LETSENCRYPT_HOST=logs.$DOMAIN
      # - DOZZLE_USERNAME=$DOZZLE_USERNAME
      # - DOZZLE_PASSWORD=$DOZZLE_PASSWORD
    networks:
      crosslab:

volumes:
  conf:
  vhost:
  html:
  certs:
  auth_service_node_modules_dev:
  auth_service_database_dev:
  device_service_node_modules_dev:
  device_service_database_dev:
  experiment_service_node_modules_dev:
  experiment_service_database_dev:
  federation_service_node_modules_dev:
  federation_service_database_dev:
  update_service_node_modules_dev:
  update_service_database_dev:

networks:
  crosslab: