name: Build and Publish Update Service

on:
  push:
    branches:
      - main
    paths:
      - "services/update/**"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create .npmrc
        run: |
          touch ./services/update/.npmrc
          echo //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }} >> ./services/update/.npmrc
          echo @cross-lab-project:registry=https://npm.pkg.github.com >> ./services/update/.npmrc
          echo always-auth=true >> ./services/update/.npmrc
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: crosslab/update-service:latest
          context: ./services/update
          file: ./services/update/Dockerfile