name: CrossLab SOA Client - Lint

on:
  push:
    branches:
      - main
    paths:
      - "clients/soa/python/**"
      - ".github/workflows/clients-soa-python-lint.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Lint with tox
        working-directory: clients/soa/python
        run: tox -e lint