name: CrossLab SOA Client - Test

on:
  push:
    branches:
      - main
    paths:
      - "clients/soa/python/**"
      - ".github/workflows/clients-soa-python-test.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - name: Install aiortc dependencies
        run: |
          sudo apt-get install -y libavdevice-dev libavfilter-dev libopus-dev libvpx-dev pkg-config
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Test with tox
        working-directory: clients/soa/python
        run: tox
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: python_soa_client
          working-directory: clients/soa/python