name: Deploy

concurrency: 
  group: development_environment
  cancel-in-progress: true

on:
  workflow_run:
    workflows: ["Build and Publish Device Service","Build and Publish Experiment Service","Build and Publish Federation Service","Build and Publish Auth Service","Build and Publish Gateway Service"]
    types:
      - completed
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "deploy/docker-compose/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run deploy.sh
        run: ./deploy/docker-compose/deploy_goldi.sh
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
          DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }}
          EMAIL: ${{ secrets.EMAIL }}
          DOMAIN: ${{ secrets.DOMAIN }}